feature(io): Pairwise comparison of lists in dictionaries
In making #1157 some precision errors were thrown on OSX and Windows.

I tried switching to `topostats.io.dict_almost_equal()` but we still get the same error as the `abs_tol` isn't yet applied to elements of a list...

```
FAILED tests/test_filters_minicircle.py::test_get_threshold_stddev - AssertionError: assert False
 +  where False = dict_almost_equal({'below': [np.float64(-7.484708050736528)], 'above': [np.float64(0.4990958836019106)]}, {'below': [np.float64(-7.484708050736529)], 'above': [np.float64(0.4990958836019106)]}, abs_tol=1e-11)
 +    where {'below': [np.float64(-7.484708050736528)], 'above': [np.float64(0.4990958836019106)]} = <topostats.filters.Filters object at 0x139f93d60>.thresholds

```

No joy...

```
INFO     topostats:io.py:95 Comparing key below
INFO     topostats:io.py:112 Key below not equal: [np.float64(-7.484708050736528)] != [np.float64(-7.484708050736529)]
```
... the `abs_tol` and `np.close()` to which the parameter is passed is not used here.

I've extended `topostats.io.dict_almost_equal()` to perform pairwise element comparison when the values of a dictionary are a list.